POST  http://localhost:3000/books
Content-Type: application/json

{
"name":"Kitabu-Tawhid",
"author":"Ibn Baaz",
"year":"2003"
}
###
GET   http://localhost:3000/AllBooks
###
GET   http://localhost:3000/OneBook:1
###
PUT    http://localhost:3000/BBooks:1
Content-Type: application/json

{
"year":"1900"
}
###

DELETE http://localhost:3000/del:1